version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: db_redis
    tty: true
    networks:
      - synecoscope-network
    volumes:
      - "./synecoio/data:/data"

  apiserver:
    build: 
      context: ./synecoio
    image: synecoio
    container_name: synecoio
    tty: true
    networks:
      - synecoscope-network
    ports:
      - "8080:8080"
    depends_on:
      - redis

networks:
  synecoscope-network:
